# Generated by Django 4.1.13 on 2024-07-08 15:52

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('user_auth', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('auth', '0002_auto_20240708_1552'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
