# Generated by Django 5.0 on 2024-07-11 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 12, 0)),
            preserve_default=False,
        ),
    ]
